title: Blogbeiträge BAIN
author: Jennifer Amoroso
email: jennifer.amoroso@stud.fhgr.ch
description: > # this means to ignore newlines
    Ein Lerntagebuch für den Kurs Bibliotheks- und Archivinformatik HS2021

# social links
github_username:  saphirba # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
